"""empty message

Revision ID: 125ae819b78d
Revises: None
Create Date: 2015-12-14 15:51:37.366232

"""

# revision identifiers, used by Alembic.
revision = '125ae819b78d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorhosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('hostname', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=2000), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('exception', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensorhosts')
    ### end Alembic commands ###
