"""empty message

Revision ID: 24d776909e72
Revises: None
Create Date: 2016-01-28 23:17:49.446449

"""

# revision identifiers, used by Alembic.
revision = '24d776909e72'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorhosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('hostname', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=2000), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('exception', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table(u'sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sensor_sensorhosts', 'sensorhosts', ['host_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'sensors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sensor_sensorhosts', type_='foreignkey')
        batch_op.drop_column('host_id')

    op.drop_table('sensorhosts')
    ### end Alembic commands ###
